server:
  port: 0

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        type: trace
    generate-ddl: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka












